/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '135480' at '2/7/17 3:02 PM' with Gradle 3.1
 *
 * @author 135480, @date 2/7/17 3:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
   public String getSiteName(){
 return "http://combination-s2t.bluemix.net";
}
    
 public String getFileName(){
 return "trial.wav";
}
}
